import { defineStore } from 'pinia'

export interface Product {
  id: number
  name: string
  slug: string
  price: number
  regularPrice?: number
  image: string
  images?: string[]
  category: string
  description: string
  shortDescription: string
  inStock: boolean
  stockQuantity: number
  sku: string
  prescriptionRequired?: boolean
  activeIngredients?: string[]
  dosage?: string
  manufacturer?: string
  rating?: number
  reviewCount?: number
}

export interface ProductsState {
  products: Product[]
  categories: string[]
  loading: boolean
  currentProduct: Product | null
  filters: {
    category: string
    minPrice: number
    maxPrice: number
    inStock: boolean
    prescriptionRequired: boolean
  }
}

export const useProductsStore = defineStore('products', {
  state: (): ProductsState => ({
    products: [],
    categories: [],
    loading: false,
    currentProduct: null,
    filters: {
      category: '',
      minPrice: 0,
      maxPrice: 10000,
      inStock: true,
      prescriptionRequired: false
    }
  }),

  getters: {
    filteredProducts: (state) => {
      return state.products.filter(product => {
        const matchesCategory = !state.filters.category || product.category === state.filters.category
        const matchesPrice = product.price >= state.filters.minPrice && product.price <= state.filters.maxPrice
        const matchesStock = !state.filters.inStock || product.inStock
        const matchesPrescription = !state.filters.prescriptionRequired || product.prescriptionRequired

        return matchesCategory && matchesPrice && matchesStock && matchesPrescription
      })
    },

    featuredProducts: (state) => {
      return state.products.filter(product => product.rating && product.rating >= 3.5).slice(0, 8)
    },

    productsByCategory: (state) => (category: string) => {
      return state.products.filter(product => product.category === category)
    }
  },

  actions: {
    async fetchProducts() {
      this.loading = true
      try {
        // Simuler appel API WooCommerce
        await new Promise(resolve => setTimeout(resolve, 1000))

        // Mock products data
        this.products = [
          {
            id: 1,
            name: 'Doliprane',
            slug: 'doliprane',
            price: 1050,
            regularPrice: 1250,
            image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
            category: 'Antibiotiques',
            description: 'Doliprane est utilisé pour traiter diverses affections.',
            shortDescription: 'Doliprane - médicament de qualité',
            inStock: true,
            stockQuantity: 21,
            sku: 'SKU-001',
            prescriptionRequired: false,
            activeIngredients: [
              'Paracétamol',
            ],
            dosage: '500mg',
            manufacturer: 'NutriHealth',
            rating: 4.5,
            reviewCount: 6,
          },
          {
            id: 2,
            name: 'Efferalgan',
            slug: 'efferalgan',
            price: 1100,
            regularPrice: 1300,
            image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
            category: 'Vitamines',
            description: 'Efferalgan est utilisé pour traiter diverses affections.',
            shortDescription: 'Efferalgan - médicament de qualité',
            inStock: true,
            stockQuantity: 22,
            sku: 'SKU-002',
            prescriptionRequired: false,
            activeIngredients: [
              'Paracétamol',
            ],
            dosage: '500mg',
            manufacturer: 'MediPharm',
            rating: 5,
            reviewCount: 7,
          },
          {
            id: 3,
            name: 'Advil',
            slug: 'advil',
            price: 1150,
            regularPrice: 1350,
            image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
            category: 'Psychotropes',
            description: 'Advil est utilisé pour traiter diverses affections.',
            shortDescription: 'Advil - médicament de qualité',
            inStock: true,
            stockQuantity: 23,
            sku: 'SKU-003',
            prescriptionRequired: false,
            activeIngredients: [
              'Ibuprofène',
            ],
            dosage: '500mg',
            manufacturer: 'MediTech',
            rating: 3.8,
            reviewCount: 8,
          },
          {
            id: 4,
            name: 'Amoxicilline Sandoz',
            slug: 'amoxicilline-sandoz',
            price: 1200,
            regularPrice: 1400,
            image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
            category: 'Cardiovasculaires',
            description: 'Amoxicilline Sandoz est utilisé pour traiter diverses affections.',
            shortDescription: 'Amoxicilline Sandoz - médicament de qualité',
            inStock: true,
            stockQuantity: 24,
            sku: 'SKU-004',
            prescriptionRequired: true,
            activeIngredients: [
              'Amoxicilline',
            ],
            dosage: '500mg',
            manufacturer: 'HealthPlus',
            rating: 3.9,
            reviewCount: 9,
          },
          {
            id: 5,
            name: 'Claritin',
            slug: 'claritin',
            price: 1250,
            regularPrice: 1450,
            image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
            category: 'Antiallergiques',
            description: 'Claritin est utilisé pour traiter diverses affections.',
            shortDescription: 'Claritin - médicament de qualité',
            inStock: true,
            stockQuantity: 25,
            sku: 'SKU-005',
            prescriptionRequired: false,
            activeIngredients: [
              'Loratadine',
            ],
            dosage: '500mg',
            manufacturer: 'BioPharma',
            rating: 3.5,
            reviewCount: 10,
          },
          {
            id: 6,
            name: 'Mopral',
            slug: 'mopral',
            price: 1300,
            regularPrice: 1500,
            image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
            category: 'Antidouleurs',
            description: 'Mopral est utilisé pour traiter diverses affections.',
            shortDescription: 'Mopral - médicament de qualité',
            inStock: true,
            stockQuantity: 26,
            sku: 'SKU-006',
            prescriptionRequired: false,
            activeIngredients: [
              'Oméprazole',
            ],
            dosage: '500mg',
            manufacturer: 'PharmaCorp',
            rating: 3.6,
            reviewCount: 11,
          },
          {
            id: 7,
            name: 'Zyrtec',
            slug: 'zyrtec',
            price: 1350,
            regularPrice: 1550,
            image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
            category: 'Antibiotiques',
            description: 'Zyrtec est utilisé pour traiter diverses affections.',
            shortDescription: 'Zyrtec - médicament de qualité',
            inStock: true,
            stockQuantity: 27,
            sku: 'SKU-007',
            prescriptionRequired: false,
            activeIngredients: [
              'Cétirizine',
            ],
            dosage: '500mg',
            manufacturer: 'NutriHealth',
            rating: 3.7,
            reviewCount: 12,
          },
          {
            id: 8,
            name: 'Augmentin',
            slug: 'augmentin',
            price: 1400,
            regularPrice: 1600,
            image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
            category: 'Vitamines',
            description: 'Augmentin est utilisé pour traiter diverses affections.',
            shortDescription: 'Augmentin - médicament de qualité',
            inStock: true,
            stockQuantity: 28,
            sku: 'SKU-008',
            prescriptionRequired: true,
            activeIngredients: [
              'Amoxicilline',
              'Acide clavulanique',
            ],
            dosage: '500mg',
            manufacturer: 'MediPharm',
            rating: 3.8,
            reviewCount: 13,
          },
          {
            id: 9,
            name: 'Séroquel',
            slug: 'seroquel',
            price: 1450,
            regularPrice: 1650,
            image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
            category: 'Psychotropes',
            description: 'Séroquel est utilisé pour traiter diverses affections.',
            shortDescription: 'Séroquel - médicament de qualité',
            inStock: true,
            stockQuantity: 29,
            sku: 'SKU-009',
            prescriptionRequired: false,
            activeIngredients: [
              'Quétiapine',
            ],
            dosage: '500mg',
            manufacturer: 'MediTech',
            rating: 3.9,
            reviewCount: 14,
          },
          {
            id: 10,
            name: 'Lévothyrox',
            slug: 'levothyrox',
            price: 1500,
            regularPrice: 1700,
            image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
            category: 'Cardiovasculaires',
            description: 'Lévothyrox est utilisé pour traiter diverses affections.',
            shortDescription: 'Lévothyrox - médicament de qualité',
            inStock: true,
            stockQuantity: 30,
            sku: 'SKU-010',
            prescriptionRequired: false,
            activeIngredients: [
              'Lévothyroxine',
            ],
            dosage: '500mg',
            manufacturer: 'HealthPlus',
            rating: 3.5,
            reviewCount: 15,
          },
          {
            id: 11,
            name: 'Glucophage',
            slug: 'glucophage',
            price: 1550,
            regularPrice: 1750,
            image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
            category: 'Antiallergiques',
            description: 'Glucophage est utilisé pour traiter diverses affections.',
            shortDescription: 'Glucophage - médicament de qualité',
            inStock: true,
            stockQuantity: 31,
            sku: 'SKU-011',
            prescriptionRequired: false,
            activeIngredients: [
              'Metformine',
            ],
            dosage: '500mg',
            manufacturer: 'BioPharma',
            rating: 3.6,
            reviewCount: 16,
          },
          {
            id: 12,
            name: 'Prinivil',
            slug: 'prinivil',
            price: 1600,
            regularPrice: 1800,
            image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
            category: 'Antidouleurs',
            description: 'Prinivil est utilisé pour traiter diverses affections.',
            shortDescription: 'Prinivil - médicament de qualité',
            inStock: true,
            stockQuantity: 32,
            sku: 'SKU-012',
            prescriptionRequired: true,
            activeIngredients: [
              'Lisinopril',
            ],
            dosage: '500mg',
            manufacturer: 'PharmaCorp',
            rating: 3.7,
            reviewCount: 17,
          },
          {
            id: 13,
            name: 'Loxen',
            slug: 'loxen',
            price: 1650,
            regularPrice: 1850,
            image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
            category: 'Antibiotiques',
            description: 'Loxen est utilisé pour traiter diverses affections.',
            shortDescription: 'Loxen - médicament de qualité',
            inStock: true,
            stockQuantity: 33,
            sku: 'SKU-013',
            prescriptionRequired: false,
            activeIngredients: [
              'Loxapine',
            ],
            dosage: '500mg',
            manufacturer: 'NutriHealth',
            rating: 3.8,
            reviewCount: 18,
          },
          {
            id: 14,
            name: 'Zestril',
            slug: 'zestril',
            price: 1700,
            regularPrice: 1900,
            image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
            category: 'Vitamines',
            description: 'Zestril est utilisé pour traiter diverses affections.',
            shortDescription: 'Zestril - médicament de qualité',
            inStock: true,
            stockQuantity: 34,
            sku: 'SKU-014',
            prescriptionRequired: false,
            activeIngredients: [
              'Lisinopril',
            ],
            dosage: '500mg',
            manufacturer: 'MediPharm',
            rating: 3.9,
            reviewCount: 19,
          },
          {
            id: 15,
            name: 'Cardensiel',
            slug: 'cardensiel',
            price: 1750,
            regularPrice: 1950,
            image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
            category: 'Psychotropes',
            description: 'Cardensiel est utilisé pour traiter diverses affections.',
            shortDescription: 'Cardensiel - médicament de qualité',
            inStock: true,
            stockQuantity: 35,
            sku: 'SKU-015',
            prescriptionRequired: false,
            activeIngredients: [
              'Perindopril',
            ],
            dosage: '500mg',
            manufacturer: 'MediTech',
            rating: 3.5,
            reviewCount: 20,
          },
          {
            id: 16,
            name: 'Tramadol Mylan',
            slug: 'tramadol-mylan',
            price: 1800,
            regularPrice: 2000,
            image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
            category: 'Cardiovasculaires',
            description: 'Tramadol Mylan est utilisé pour traiter diverses affections.',
            shortDescription: 'Tramadol Mylan - médicament de qualité',
            inStock: true,
            stockQuantity: 36,
            sku: 'SKU-016',
            prescriptionRequired: true,
            activeIngredients: [
              'Tramadol',
            ],
            dosage: '500mg',
            manufacturer: 'HealthPlus',
            rating: 3.6,
            reviewCount: 21,
          },
          {
            id: 17,
            name: 'Singulair',
            slug: 'singulair',
            price: 1850,
            regularPrice: 2050,
            image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
            category: 'Antiallergiques',
            description: 'Singulair est utilisé pour traiter diverses affections.',
            shortDescription: 'Singulair - médicament de qualité',
            inStock: true,
            stockQuantity: 37,
            sku: 'SKU-017',
            prescriptionRequired: false,
            activeIngredients: [
              'Montélukast',
            ],
            dosage: '500mg',
            manufacturer: 'BioPharma',
            rating: 3.7,
            reviewCount: 22,
          },
          {
            id: 18,
            name: 'Lasilix',
            slug: 'lasilix',
            price: 1900,
            regularPrice: 2100,
            image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
            category: 'Antidouleurs',
            description: 'Lasilix est utilisé pour traiter diverses affections.',
            shortDescription: 'Lasilix - médicament de qualité',
            inStock: true,
            stockQuantity: 38,
            sku: 'SKU-018',
            prescriptionRequired: false,
            activeIngredients: [
              'Furosémide',
            ],
            dosage: '500mg',
            manufacturer: 'PharmaCorp',
            rating: 3.8,
            reviewCount: 23,
          },
          {
            id: 19,
            name: 'Durogesic',
            slug: 'durogesic',
            price: 1950,
            regularPrice: 2150,
            image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
            category: 'Antibiotiques',
            description: 'Durogesic est utilisé pour traiter diverses affections.',
            shortDescription: 'Durogesic - médicament de qualité',
            inStock: true,
            stockQuantity: 39,
            sku: 'SKU-019',
            prescriptionRequired: false,
            activeIngredients: [
              'Fentanyl',
            ],
            dosage: '500mg',
            manufacturer: 'NutriHealth',
            rating: 3.9,
            reviewCount: 24,
          },
          {
            id: 20,
            name: 'Kétum',
            slug: 'ketum',
            price: 2000,
            regularPrice: 2200,
            image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
            category: 'Vitamines',
            description: 'Kétum est utilisé pour traiter diverses affections.',
            shortDescription: 'Kétum - médicament de qualité',
            inStock: true,
            stockQuantity: 40,
            sku: 'SKU-020',
            prescriptionRequired: true,
            activeIngredients: [
              'Kétoprofène',
            ],
            dosage: '500mg',
            manufacturer: 'MediPharm',
            rating: 3.5,
            reviewCount: 25,
          },
          {
            id: 21,
            name: 'Seroplex',
            slug: 'seroplex',
            price: 2050,
            regularPrice: 2250,
            image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
            category: 'Psychotropes',
            description: 'Seroplex est utilisé pour traiter diverses affections.',
            shortDescription: 'Seroplex - médicament de qualité',
            inStock: true,
            stockQuantity: 41,
            sku: 'SKU-021',
            prescriptionRequired: false,
            activeIngredients: [
              'Escitalopram',
            ],
            dosage: '500mg',
            manufacturer: 'MediTech',
            rating: 3.6,
            reviewCount: 26,
          },
          {
            id: 22,
            name: 'Zantac',
            slug: 'zantac',
            price: 2100,
            regularPrice: 2300,
            image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
            category: 'Cardiovasculaires',
            description: 'Zantac est utilisé pour traiter diverses affections.',
            shortDescription: 'Zantac - médicament de qualité',
            inStock: true,
            stockQuantity: 42,
            sku: 'SKU-022',
            prescriptionRequired: false,
            activeIngredients: [
              'Ranitidine',
            ],
            dosage: '500mg',
            manufacturer: 'HealthPlus',
            rating: 3.7,
            reviewCount: 27,
          },
          {
            id: 23,
            name: 'Cipro',
            slug: 'cipro',
            price: 2150,
            regularPrice: 2350,
            image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
            category: 'Antiallergiques',
            description: 'Cipro est utilisé pour traiter diverses affections.',
            shortDescription: 'Cipro - médicament de qualité',
            inStock: true,
            stockQuantity: 43,
            sku: 'SKU-023',
            prescriptionRequired: false,
            activeIngredients: [
              'Ciprofloxacine',
            ],
            dosage: '500mg',
            manufacturer: 'BioPharma',
            rating: 3.8,
            reviewCount: 28,
          },
          {
            id: 24,
            name: 'Flagyl',
            slug: 'flagyl',
            price: 2200,
            regularPrice: 2400,
            image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
            category: 'Antidouleurs',
            description: 'Flagyl est utilisé pour traiter diverses affections.',
            shortDescription: 'Flagyl - médicament de qualité',
            inStock: true,
            stockQuantity: 44,
            sku: 'SKU-024',
            prescriptionRequired: true,
            activeIngredients: [
              'Métronidazole',
            ],
            dosage: '500mg',
            manufacturer: 'PharmaCorp',
            rating: 3.9,
            reviewCount: 29,
          },
          {
            id: 25,
            name: 'Novorapid',
            slug: 'novorapid',
            price: 2250,
            regularPrice: 2450,
            image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
            category: 'Antibiotiques',
            description: 'Novorapid est utilisé pour traiter diverses affections.',
            shortDescription: 'Novorapid - médicament de qualité',
            inStock: true,
            stockQuantity: 45,
            sku: 'SKU-025',
            prescriptionRequired: false,
            activeIngredients: [
              'Insuline aspart',
            ],
            dosage: '500mg',
            manufacturer: 'NutriHealth',
            rating: 3.5,
            reviewCount: 30,
          },
          {
            id: 26,
            name: 'Solupred',
            slug: 'solupred',
            price: 2300,
            regularPrice: 2500,
            image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
            category: 'Vitamines',
            description: 'Solupred est utilisé pour traiter diverses affections.',
            shortDescription: 'Solupred - médicament de qualité',
            inStock: true,
            stockQuantity: 46,
            sku: 'SKU-026',
            prescriptionRequired: false,
            activeIngredients: [
              'Prednisone',
            ],
            dosage: '500mg',
            manufacturer: 'MediPharm',
            rating: 3.6,
            reviewCount: 31,
          },
          {
            id: 27,
            name: 'Telfast',
            slug: 'telfast',
            price: 2350,
            regularPrice: 2550,
            image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
            category: 'Psychotropes',
            description: 'Telfast est utilisé pour traiter diverses affections.',
            shortDescription: 'Telfast - médicament de qualité',
            inStock: true,
            stockQuantity: 47,
            sku: 'SKU-027',
            prescriptionRequired: false,
            activeIngredients: [
              'Fexofénadine',
            ],
            dosage: '500mg',
            manufacturer: 'MediTech',
            rating: 3.7,
            reviewCount: 32,
          },
          {
            id: 28,
            name: 'Celestamine',
            slug: 'celestamine',
            price: 2400,
            regularPrice: 2600,
            image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
            category: 'Cardiovasculaires',
            description: 'Celestamine est utilisé pour traiter diverses affections.',
            shortDescription: 'Celestamine - médicament de qualité',
            inStock: true,
            stockQuantity: 48,
            sku: 'SKU-028',
            prescriptionRequired: true,
            activeIngredients: [
              'étaméthasone',
              'Diphénhydramine',
            ],
            dosage: '500mg',
            manufacturer: 'HealthPlus',
            rating: 3.8,
            reviewCount: 33,
          },
          {
            id: 29,
            name: 'Motilium',
            slug: 'motilium',
            price: 2450,
            regularPrice: 2650,
            image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
            category: 'Antiallergiques',
            description: 'Motilium est utilisé pour traiter diverses affections.',
            shortDescription: 'Motilium - médicament de qualité',
            inStock: true,
            stockQuantity: 49,
            sku: 'SKU-029',
            prescriptionRequired: false,
            activeIngredients: [
              'Dompéridone',
            ],
            dosage: '500mg',
            manufacturer: 'BioPharma',
            rating: 3.9,
            reviewCount: 34,
          },
          {
            id: 30,
            name: 'Elocon',
            slug: 'elocon',
            price: 2500,
            regularPrice: 2700,
            image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
            category: 'Antidouleurs',
            description: 'Elocon est utilisé pour traiter diverses affections.',
            shortDescription: 'Elocon - médicament de qualité',
            inStock: true,
            stockQuantity: 50,
            sku: 'SKU-030',
            prescriptionRequired: false,
            activeIngredients: [
              'Méthylprednisolone',
            ],
            dosage: '500mg',
            manufacturer: 'PharmaCorp',
            rating: 3.5,
            reviewCount: 35,
          },
          {
            id: 31,
            name: 'Cilazapril',
            slug: 'cilazapril',
            price: 2550,
            regularPrice: 2750,
            image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
            category: 'Antibiotiques',
            description: 'Cilazapril est utilisé pour traiter diverses affections.',
            shortDescription: 'Cilazapril - médicament de qualité',
            inStock: true,
            stockQuantity: 51,
            sku: 'SKU-031',
            prescriptionRequired: false,
            activeIngredients: [
              'Cilazapril',
            ],
            dosage: '500mg',
            manufacturer: 'NutriHealth',
            rating: 3.6,
            reviewCount: 36,
          },
          {
            id: 32,
            name: 'Myolastan',
            slug: 'myolastan',
            price: 2600,
            regularPrice: 2800,
            image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
            category: 'Vitamines',
            description: 'Myolastan est utilisé pour traiter diverses affections.',
            shortDescription: 'Myolastan - médicament de qualité',
            inStock: true,
            stockQuantity: 52,
            sku: 'SKU-032',
            prescriptionRequired: true,
            activeIngredients: [
              'Tiemonium',
            ],
            dosage: '500mg',
            manufacturer: 'MediPharm',
            rating: 3.7,
            reviewCount: 37,
          },
          {
            id: 33,
            name: 'Tenormine',
            slug: 'tenormine',
            price: 2650,
            regularPrice: 2850,
            image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
            category: 'Psychotropes',
            description: 'Tenormine est utilisé pour traiter diverses affections.',
            shortDescription: 'Tenormine - médicament de qualité',
            inStock: true,
            stockQuantity: 53,
            sku: 'SKU-033',
            prescriptionRequired: false,
            activeIngredients: [
              'Aténolol',
            ],
            dosage: '500mg',
            manufacturer: 'MediTech',
            rating: 3.8,
            reviewCount: 38,
          },
          {
            id: 34,
            name: 'Nexium',
            slug: 'nexium',
            price: 2700,
            regularPrice: 2900,
            image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
            category: 'Cardiovasculaires',
            description: 'Nexium est utilisé pour traiter diverses affections.',
            shortDescription: 'Nexium - médicament de qualité',
            inStock: true,
            stockQuantity: 54,
            sku: 'SKU-034',
            prescriptionRequired: false,
            activeIngredients: [
              'Esoméprazole',
            ],
            dosage: '500mg',
            manufacturer: 'HealthPlus',
            rating: 3.9,
            reviewCount: 39,
          },
          {
            id: 35,
            name: 'Zoloft',
            slug: 'zoloft',
            price: 2750,
            regularPrice: 2950,
            image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
            category: 'Antiallergiques',
            description: 'Zoloft est utilisé pour traiter diverses affections.',
            shortDescription: 'Zoloft - médicament de qualité',
            inStock: true,
            stockQuantity: 55,
            sku: 'SKU-035',
            prescriptionRequired: false,
            activeIngredients: [
              'Sertraline',
            ],
            dosage: '500mg',
            manufacturer: 'BioPharma',
            rating: 3.5,
            reviewCount: 40,
          },
          {
            id: 36,
            name: 'Vasotec',
            slug: 'vasotec',
            price: 2800,
            regularPrice: 3000,
            image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
            category: 'Antidouleurs',
            description: 'Vasotec est utilisé pour traiter diverses affections.',
            shortDescription: 'Vasotec - médicament de qualité',
            inStock: true,
            stockQuantity: 56,
            sku: 'SKU-036',
            prescriptionRequired: true,
            activeIngredients: [
              'Enalapril',
            ],
            dosage: '500mg',
            manufacturer: 'PharmaCorp',
            rating: 3.6,
            reviewCount: 41,
          },
          {
            id: 37,
            name: 'Ventolin',
            slug: 'ventolin',
            price: 2850,
            regularPrice: 3050,
            image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
            category: 'Antibiotiques',
            description: 'Ventolin est utilisé pour traiter diverses affections.',
            shortDescription: 'Ventolin - médicament de qualité',
            inStock: true,
            stockQuantity: 57,
            sku: 'SKU-037',
            prescriptionRequired: false,
            activeIngredients: [
              'Salbutamol',
            ],
            dosage: '500mg',
            manufacturer: 'NutriHealth',
            rating: 3.7,
            reviewCount: 42,
          },
          {
            id: 38,
            name: 'Prozac',
            slug: 'prozac',
            price: 2900,
            regularPrice: 3100,
            image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
            category: 'Vitamines',
            description: 'Prozac est utilisé pour traiter diverses affections.',
            shortDescription: 'Prozac - médicament de qualité',
            inStock: true,
            stockQuantity: 58,
            sku: 'SKU-038',
            prescriptionRequired: false,
            activeIngredients: [
              'Fluoxétine',
            ],
            dosage: '500mg',
            manufacturer: 'MediPharm',
            rating: 3.8,
            reviewCount: 43,
          },
          {
            id: 39,
            name: 'Inderal',
            slug: 'inderal',
            price: 2950,
            regularPrice: 3150,
            image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
            category: 'Psychotropes',
            description: 'Inderal est utilisé pour traiter diverses affections.',
            shortDescription: 'Inderal - médicament de qualité',
            inStock: true,
            stockQuantity: 59,
            sku: 'SKU-039',
            prescriptionRequired: false,
            activeIngredients: [
              'Propranolol',
            ],
            dosage: '500mg',
            manufacturer: 'MediTech',
            rating: 3.9,
            reviewCount: 44,
          },
          {
            id: 40,
            name: 'Actrapid',
            slug: 'actrapid',
            price: 3000,
            regularPrice: 3200,
            image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
            category: 'Cardiovasculaires',
            description: 'Actrapid est utilisé pour traiter diverses affections.',
            shortDescription: 'Actrapid - médicament de qualité',
            inStock: true,
            stockQuantity: 60,
            sku: 'SKU-040',
            prescriptionRequired: true,
            activeIngredients: [
              'Insuline humaine',
            ],
            dosage: '500mg',
            manufacturer: 'HealthPlus',
            rating: 3.5,
            reviewCount: 45,
          },
          {
            id: 41,
            name: 'Tremfya',
            slug: 'tremfya',
            price: 3050,
            regularPrice: 3250,
            image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
            category: 'Antiallergiques',
            description: 'Tremfya est utilisé pour traiter diverses affections.',
            shortDescription: 'Tremfya - médicament de qualité',
            inStock: true,
            stockQuantity: 61,
            sku: 'SKU-041',
            prescriptionRequired: false,
            activeIngredients: [
              'Guselkumab',
            ],
            dosage: '500mg',
            manufacturer: 'BioPharma',
            rating: 3.6,
            reviewCount: 46,
          },
          {
            id: 42,
            name: 'Lyrica',
            slug: 'lyrica',
            price: 3100,
            regularPrice: 3300,
            image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
            category: 'Antidouleurs',
            description: 'Lyrica est utilisé pour traiter diverses affections.',
            shortDescription: 'Lyrica - médicament de qualité',
            inStock: true,
            stockQuantity: 62,
            sku: 'SKU-042',
            prescriptionRequired: false,
            activeIngredients: [
              'Prégabaline',
            ],
            dosage: '500mg',
            manufacturer: 'PharmaCorp',
            rating: 3.7,
            reviewCount: 47,
          },
          {
            id: 43,
            name: 'Temesta',
            slug: 'temesta',
            price: 3150,
            regularPrice: 3350,
            image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
            category: 'Antibiotiques',
            description: 'Temesta est utilisé pour traiter diverses affections.',
            shortDescription: 'Temesta - médicament de qualité',
            inStock: true,
            stockQuantity: 63,
            sku: 'SKU-043',
            prescriptionRequired: false,
            activeIngredients: [
              'Lorazépam',
            ],
            dosage: '500mg',
            manufacturer: 'NutriHealth',
            rating: 3.8,
            reviewCount: 48,
          },
          {
            id: 44,
            name: 'Xanax',
            slug: 'xanax',
            price: 3200,
            regularPrice: 3400,
            image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
            category: 'Vitamines',
            description: 'Xanax est utilisé pour traiter diverses affections.',
            shortDescription: 'Xanax - médicament de qualité',
            inStock: true,
            stockQuantity: 64,
            sku: 'SKU-044',
            prescriptionRequired: true,
            activeIngredients: [
              'Alprazolam',
            ],
            dosage: '500mg',
            manufacturer: 'MediPharm',
            rating: 3.9,
            reviewCount: 49,
          },
          {
            id: 45,
            name: 'Eurexin',
            slug: 'eurexin',
            price: 3250,
            regularPrice: 3450,
            image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
            category: 'Psychotropes',
            description: 'Eurexin est utilisé pour traiter diverses affections.',
            shortDescription: 'Eurexin - médicament de qualité',
            inStock: true,
            stockQuantity: 65,
            sku: 'SKU-045',
            prescriptionRequired: false,
            activeIngredients: [
              'Trimebutine',
            ],
            dosage: '500mg',
            manufacturer: 'MediTech',
            rating: 3.5,
            reviewCount: 50,
          },
          {
            id: 46,
            name: 'Dafalgan',
            slug: 'dafalgan',
            price: 3300,
            regularPrice: 3500,
            image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
            category: 'Cardiovasculaires',
            description: 'Dafalgan est utilisé pour traiter diverses affections.',
            shortDescription: 'Dafalgan - médicament de qualité',
            inStock: true,
            stockQuantity: 66,
            sku: 'SKU-046',
            prescriptionRequired: false,
            activeIngredients: [
              'Paracétamol',
            ],
            dosage: '500mg',
            manufacturer: 'HealthPlus',
            rating: 3.6,
            reviewCount: 51,
          },
          {
            id: 47,
            name: 'Neurontin',
            slug: 'neurontin',
            price: 3350,
            regularPrice: 3550,
            image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
            category: 'Antiallergiques',
            description: 'Neurontin est utilisé pour traiter diverses affections.',
            shortDescription: 'Neurontin - médicament de qualité',
            inStock: true,
            stockQuantity: 67,
            sku: 'SKU-047',
            prescriptionRequired: false,
            activeIngredients: [
              'Gabapentine',
            ],
            dosage: '500mg',
            manufacturer: 'BioPharma',
            rating: 3.7,
            reviewCount: 52,
          },
          {
            id: 48,
            name: 'Topalgic',
            slug: 'topalgic',
            price: 3400,
            regularPrice: 3600,
            image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
            category: 'Antidouleurs',
            description: 'Topalgic est utilisé pour traiter diverses affections.',
            shortDescription: 'Topalgic - médicament de qualité',
            inStock: true,
            stockQuantity: 68,
            sku: 'SKU-048',
            prescriptionRequired: true,
            activeIngredients: [
              'Tramadol',
            ],
            dosage: '500mg',
            manufacturer: 'PharmaCorp',
            rating: 3.8,
            reviewCount: 53,
          },
          {
            id: 49,
            name: 'Naproxène EG',
            slug: 'naproxene-eg',
            price: 3450,
            regularPrice: 3650,
            image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
            category: 'Antibiotiques',
            description: 'Naproxène EG est utilisé pour traiter diverses affections.',
            shortDescription: 'Naproxène EG - médicament de qualité',
            inStock: true,
            stockQuantity: 69,
            sku: 'SKU-049',
            prescriptionRequired: false,
            activeIngredients: [
              'Naproxène',
            ],
            dosage: '500mg',
            manufacturer: 'NutriHealth',
            rating: 3.9,
            reviewCount: 54,
          },
          {
            id: 50,
            name: 'Zofran',
            slug: 'zofran',
            price: 3500,
            regularPrice: 3700,
            image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
            category: 'Vitamines',
            description: 'Zofran est utilisé pour traiter diverses affections.',
            shortDescription: 'Zofran - médicament de qualité',
            inStock: true,
            stockQuantity: 70,
            sku: 'SKU-050',
            prescriptionRequired: false,
            activeIngredients: [
              'Ondansétron',
            ],
            dosage: '500mg',
            manufacturer: 'MediPharm',
            rating: 3.5,
            reviewCount: 55,
          },

        ]

        this.categories = [...new Set(this.products.map(p => p.category))]
      } catch (error) {
        throw new Error('Erreur lors du chargement des produits')
      } finally {
        this.loading = false
      }
    },

    async fetchProduct(id: number) {
      const product = this.products.find(p => p.id === id)
      if (product) {
        this.currentProduct = product
      } else {
        // Simuler appel API pour un produit spécifique
        await new Promise(resolve => setTimeout(resolve, 500))
        this.currentProduct = this.products[0] // Fallback
      }
    },

    updateFilters(newFilters: Partial<ProductsState['filters']>) {
      this.filters = { ...this.filters, ...newFilters }
    },

    clearFilters() {
      this.filters = {
        category: '',
        minPrice: 0,
        maxPrice: 1000,
        inStock: true,
        prescriptionRequired: false
      }
    }
  }
})